#!/bin/sh

#module load craype-hugepages64M

export BOOST_INSTALL=/home/users/p02119/development/install/boost/
export AMPP_INSTALL=/home/users/p02119/development/install/amppvar/
#export AMPP_INSTALL=/home/users/p02119/development/install/ampp/
export LIBCDS_INSTALL=/home/users/p02119/development/cds-2.1.0/
export BOOST_ROOT=$BOOST_INSTALL

export CRAYPE_LINK_TYPE=dynamic
#-DCMAKE_CXX_FLAGS:STRING="-std=c++11 -ggdb -UAMPLUSPLUS_ENABLE_PERFORMANCE_COUNTERS -DAMPLUSPLUS_BUILTIN_ATOMICS -UDC_USE_PRIORITY -UDC_USE_EXPLICIT_POLLING -UDC_USE_HANDLERS_PENDING -UDC_USE_AGGRESSIVE_PRIORITY -UDC_USE_POLL_ONCE" \
#-DCMAKE_CXX_FLAGS:STRING="-mavx -march=corei7-avx -mtune=corei7-avx -std=c++11 -O3 -Ofast -ffast-math -funroll-loops -DAMPLUSPLUS_ENABLE_PERFORMANCE_COUNTERS -DAMPLUSPLUS_BUILTIN_ATOMICS -UDC_USE_PRIORITY -UDC_USE_EXPLICIT_POLLING -UDC_USE_HANDLERS_PENDING -UDC_USE_AGGRESSIVE_PRIORITY -UDC_USE_POLL_ONCE -DMIS_PRIORITY" \

#DNEW_GRAPH500_SPEC
#-DDISABLE_SELF_SEND_CHECK
#-DMIS_PRIORITY
#-DMIS_STATS
#-DTC_STATS
#-DTC_NO_ORDERING
#TC_ALGO_SUCSUC
#-DNO_COALESCING
#-DCOLLECT_STATS

rm -rf CMakeCache.txt CMakeFiles
make clean
cmake .. -D-DCMAKE_BUILD_TYPE=Release -DAM++_LIBRARY:FILEPATH=$AMPP_INSTALL/lib/libampp.a \
-DLIBCDS_INCLUDE_DIR:PATH=$LIBCDS_INSTALL \
-DLIBCDS_LIBRARY:FILEPATH=/home/users/p02119/development/cds-2.1.0/bin/cc-amd64-linux-64/libcds.so \
-DAM++_INCLUDE_DIR:PATH=$AMPP_INSTALL/include \
-DLIBNBC_INCLUDE_DIR= \
-DCMAKE_CXX_FLAGS:STRING="-g -mavx -march=corei7-avx -mtune=corei7-avx -std=c++11 -O3 -Ofast -ffast-math -funroll-loops -UAMPLUSPLUS_ENABLE_PERFORMANCE_COUNTERS -DAMPLUSPLUS_BUILTIN_ATOMICS -UDC_USE_PRIORITY -UDC_USE_EXPLICIT_POLLING -UDC_USE_HANDLERS_PENDING -UDC_USE_AGGRESSIVE_PRIORITY -UDC_USE_POLL_ONCE -DCYCLIC_DIST -DCC_PRIORITY -DTC_STATS -DNDEBUG -DTC_NO_ORDERING -DDISABLE_SELF_SEND_CHECK -DNO_COALESCING -DCOLLECT_STATS -DCYCLE_TIME" \
-DCMAKE_EXE_LINKER_FLAGS:STRING="-L/home/users/p02119/development/cds-2.1.0/bin/cc-amd64-linux-64/ -lcds -lnuma" \
-DBoost_INCLUDE_DIR:PATH=$BOOST_INSTALL/include \
-DBoost_LIBRARY_DIR:PATH=$BOOST_INSTALL/lib \
-DBoost_RANDOM_LIBRARY_DEBUG:FILEPATH=$BOOST_INSTALL/lib/libboost_random.a \
-DBoost_RANDOM_LIBRARY_RELEASE:FILEPATH=$BOOST_INSTALL/lib/libboost_random.a \
-DBoost_SYSTEM_LIBRARY_DEBUG:FILEPATH=$BOOST_INSTALL/lib/libboost_system.a \
-DBoost_SYSTEM_LIBRARY_RELEASE:FILEPATH=$BOOST_INSTALL/lib/libboost_system.a \
-DBoost_THREAD_LIBRARY_DEBUG:FILEPATH=$BOOST_INSTALL/lib/libboost_thread.a \
-DBoost_THREAD_LIBRARY_RELEASE:FILEPATH=$BOOST_INSTALL/lib/libboost_thread.a \
-DBoost_SYSTEM_LIBRARY:FILEPATH=$BOOST_INSTALL/lib/libboost_system.a \
-DBoost_THREAD_LIBRARY:FILEPATH=$BOOST_INSTALL/lib/libboost_thread.a \
-DCMAKE_CXX_COMPILER:FILEPATH=CC \
-DCMAKE_C_COMPILER:FILEPATH=cc
#-DMPI_LIBRARY:FILEPATH=/opt/cray/mpt/7.2.6/gni/mpich-gnu/51/lib/libmpichcxx_gnu_51_mt.a  \
#-DMPI_INCLUDE_PATH:PATH=/opt/cray/mpt/7.2.6/gni/mpich-gnu/51/include/


#make mis_family VERBOSE=1
#make tc_family VERBOSE=1
#make bfs_family VERBOSE=1
make gizmo VERBOSE=1
